name: "short-link"

services:
  app:
    image: golang:1.21
    build: ..
    working_dir: /app
    volumes:
      - ../:/app
    ports:
      - "${HTTP_PORT}:8080"
      - "${GOROUTINE_WATCH_PORT}:6060"
      - "${GRAFANA_PORT}:2112"
    container_name: go_app
    depends_on:
      - rabbitmq
      - db
      - redis
    stdin_open: true
    tty: true
    stop_signal: SIGINT # Specify the signal to be sent for graceful shutdown
    stop_grace_period: 3s # Time to wait for graceful shutdown before killing the container
    restart: no
    command: [ "/wait-for-it.sh", "rabbitmq", "5672", "/wait-for-it.sh", "db", "5432", "go run ./cmd/main.go" ]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${QUEUERABBIT_PORT}:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DBNAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # Prometheus web UI
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000" # Grafana web UI
    volumes:
      - ./grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  redis_data:
