apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: [ 'sh', '-c', "until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 5; done" ]
        - name: wait-for-postgres
          image: busybox
          command: [ 'sh', '-c', "until nc -z postgres 5432; do echo waiting for postgres; sleep 5; done" ]
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
      containers:
      - image: {{ .Values.imageName }}
        name: {{ .Values.appName }}-{{ randAlpha 10 | lower }}
        ports:
          - containerPort: 80
        env:
          - name: GO_ENV
            value: production
        resources: {}
