HTTP_PORT: 8080
HTTP_PROTOCOL: http
REFERER_HOST: localhost
APP_MOD: local
REDIS:
  HOST: redis
  PORT: 8888
  USE_AUTH: false
  PASSWORD:
HASHCODE: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
DB:
  DRIVER: postgres
  HOST: postgres
  PORT: 5432
  USER: postgres
  PASSWORD: postgres
  DBNAME: slink
LOGGER:
  LOG_LEVEL: TRACE
  GRAYLOG_ACTIVE: false
  GRAYLOG_SERVER:
  GRAYLOG_STREAM: short-link
QueueRabbit:
  MAIN_QUEUE_NAME: sync
  HOST: rabbitmq
  PORT: 5672
  USER: guest
  PASSWORD: guest
APP_PATH : /Users/mehdi/Sites/short-link/