HTTP_PORT: 8000
REFERER_HOST: localhost
APP_MOD: local
REDIS:
  HOST: [localhost:7000,localhost:7001,localhost:7002]
  USE_AUTH: false
  PASSWORD:
HASHCODE : abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789