HTTP_PORT: 8080
HTTP_PROTOCOL: http
REFERER_HOST: localhost
APP_MOD: local
REDIS:
  HOST: localhost
  PORT: 6379
  USE_AUTH: false
  PASSWORD:
HASHCODE: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
DB:
  DRIVER: postgres
  HOST: localhost
  PORT: 5432
  USER: default
  PASSWORD: secret
  DBNAME: slink
LOGGER:
  LOG_LEVEL: TRACE
  GRAYLOG_ACTIVE: false
  GRAYLOG_SERVER:
  GRAYLOG_STREAM: short-link
QueueRabbit:
  MAIN_QUEUE_NAME: sync
  HOST: localhost
  PORT: 5672
  USER: guest
  PASSWORD: guest
APP_PATH : /Users/mehdi/Sites/short-link/